# docs/blog/.authors.yml
# Ce fichier définit ton profil auteur pour tous les articles du blog
authors:
  darc:
    name: Abdou Aziz Darc
    description: Géographe · Technicien Supérieur en Géomatique · Télépilote drone
    avatar: https://github.com/Darcman0.png


  mDieng:
    name: Mohamed Dieng
    description: Géomaticien · Télépilote drone
    avatar: https://github.com/mohameddieng.png


